### DISCUSSION TITLE
DB error while uploading jtl -> error: period must be greater than 0

### DISCUSSION THREAD

**Discussion by gOOrcio** [ludeknovy/jtl-reporter#176] [Q&A] [answered]
I would greatly appreciate your, @ludeknovy, help as I am stuck!
This is probably something very stupid what I am missing, but I cannot upload my kpi.jtl file: 
- I made sure that I have proper columns in CSV
- I am running the tests using Taurus/JMeter
- I tried both by UI and by cURL
- I am running the docker compose jtl-reporter on my localhost. 
- Let me know what details more do you need to investigate

I can see the error postgress is throwing, but even with data from kpi as 0 I don't see where the issue might come from.

Error:
```
jtl-reporter-be-1         | {"level":"info","message":"User 6b47492b-55d3-445b-bda3-7f5272b1efff with role admin accessing a resource with allowed roles: operator,admin"}
jtl-reporter-be-1         | {"level":"info","message":"Starting new item processing for scenario: anonymous-scenario"}
jtl-reporter-fe-1         | 192.168.16.1 - - [22/Jun/2022:19:24:57 +0000] "POST /api/projects/anonymous-project/scenarios/anonymous-scenario/items HTTP/1.1" 200 74 "-" "curl/7.68.0"
jtl-reporter-be-1         | {"level":"info","message":"POST /api/projects/anonymous-project/scenarios/anonymous-scenario/items 200 66ms","meta":{}}
jtl-reporter-be-1         | {"level":"info","message":"Starting KPI file streaming and saving to db, item_id: 5ce067ec-acf1-4677-87da-cf93a3e7eafa"}
jtl-reporter-be-1         | {"level":"info","message":"Parsed 10 records in 0.036 seconds"}
jtl-reporter-db           | 2022-06-22 19:24:58.057 UTC [53] ERROR:  period must be greater than 0
jtl-reporter-db           | 2022-06-22 19:24:58.057 UTC [53] STATEMENT:
jtl-reporter-db           |         SELECT
jtl-reporter-db           |           time_bucket($1, timestamp) as time,
jtl-reporter-db           |           samples.label,
jtl-reporter-db           |           percentile_cont(0.99) within group (order by (samples.elapsed))::real as n99,
jtl-reporter-db           |           percentile_cont(0.95) within group (order by (samples.elapsed))::real as n95,
jtl-reporter-db           |           percentile_cont(0.90) within group (order by (samples.elapsed))::real as n90,
jtl-reporter-db           |           MIN(samples.elapsed)::real as min_response,
jtl-reporter-db           |           MAX(samples.elapsed)::real as max_response,
jtl-reporter-db           |           EXTRACT(EPOCH FROM (MAX(samples.timestamp) - MIN(samples.timestamp))) as interval,
jtl-reporter-db           |           (count(*) filter (where samples.success = false)::real / count(*)::real)::real as error_rate,
jtl-reporter-db           |           AVG(samples.elapsed)::real as avg_response,
jtl-reporter-db           |           SUM(samples.sent_bytes)::bigint as bytes_sent_total,
jtl-reporter-db           |           SUM(samples.bytes)::bigint as bytes_received_total,
jtl-reporter-db           |           COUNT(*)::bigint as total
jtl-reporter-db           |         FROM jtl.samples as samples
jtl-reporter-db           |         WHERE item_id = $2
jtl-reporter-db           |         GROUP BY time, samples.label;
jtl-reporter-be-1         | error: period must be greater than 0
jtl-reporter-be-1         |     at Parser.parseErrorMessage (/src/be/node_modules/pg-protocol/dist/parser.js:287:98)
jtl-reporter-be-1         |     at Parser.handlePacket (/src/be/node_modules/pg-protocol/dist/parser.js:126:29)
jtl-reporter-be-1         |     at Parser.parse (/src/be/node_modules/pg-protocol/dist/parser.js:39:38)
jtl-reporter-be-1         |     at Socket.<anonymous> (/src/be/node_modules/pg-protocol/dist/index.js:11:42)
jtl-reporter-be-1         |     at Socket.emit (events.js:375:28)
jtl-reporter-be-1         |     at addChunk (internal/streams/readable.js:290:12)
jtl-reporter-be-1         |     at readableAddChunk (internal/streams/readable.js:265:9)
jtl-reporter-be-1         |     at Socket.Readable.push (internal/streams/readable.js:204:10)
jtl-reporter-be-1         |     at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
jtl-reporter-be-1         |   length: 98,
jtl-reporter-be-1         |   severity: 'ERROR',
jtl-reporter-be-1         |   code: '22023',
jtl-reporter-be-1         |   detail: undefined,
jtl-reporter-be-1         |   hint: undefined,
jtl-reporter-be-1         |   position: undefined,
jtl-reporter-be-1         |   internalPosition: undefined,
jtl-reporter-be-1         |   internalQuery: undefined,
jtl-reporter-be-1         |   where: undefined,
jtl-reporter-be-1         |   schema: undefined,
jtl-reporter-be-1         |   table: undefined,
jtl-reporter-be-1         |   column: undefined,
jtl-reporter-be-1         |   dataType: undefined,
jtl-reporter-be-1         |   constraint: undefined,
jtl-reporter-be-1         |   file: 'time_bucket.c',
jtl-reporter-be-1         |   line: '171',
jtl-reporter-be-1         |   routine: 'ts_timestamp_bucket'
jtl-reporter-be-1         | }
jtl-reporter-be-1         | {"level":"error","message":"Error while processing item: 5ce067ec-acf1-4677-87da-cf93a3e7eafa: Error: Error while processing dataId: 5ce067ec-acf1-4677-87da-cf93a3e7eafa for item: 5ce067ec-acf1-4677-87da-cf93a3e7eafa, error: error: period must be greater than 0"}

```

kpi.jtl
```
timeStamp,elapsed,label,responseCode,responseMessage,threadName,dataType,success,failureMessage,bytes,sentBytes,grpThreads,allThreads,URL,Latency,Hostname,IdleTime,Connect
1655925893706,90,/api/v4/anonymous-endpoint,200,,Anonymous Thread Group 1-1,text,true,,1414,370,2,2,http://192.168.50.10:8008/api/v4/anonymous-endpoint,89,4d6b0a93d8b9,0,60
1655925893706,93,/api/v4/anonymous-endpoint,200,,Anonymous Thread Group 1-2,text,true,,1414,370,2,2,http://192.168.50.10:8008/api/v4/anonymous-endpoint,93,4d6b0a93d8b9,0,60
1655925893798,20,/api/v4/anonymous-endpoint,200,,Anonymous Thread Group 1-1,text,true,,1413,370,2,2,http://192.168.50.10:8008/api/v4/anonymous-endpoint,19,4d6b0a93d8b9,0,0
1655925893801,21,/api/v4/anonymous-endpoint,200,,Anonymous Thread Group 1-2,text,true,,1413,370,2,2,http://192.168.50.10:8008/api/v4/anonymous-endpoint,20,4d6b0a93d8b9,0,0
1655925893819,19,/api/v4/anonymous-endpoint,200,,Anonymous Thread Group 1-1,text,true,,1413,370,2,2,http://192.168.50.10:8008/api/v4/anonymous-endpoint,18,4d6b0a93d8b9,0,0
1655925893822,20,/api/v4/anonymous-endpoint,200,,Anonymous Thread Group 1-2,text,true,,1413,370,2,2,http://192.168.50.10:8008/api/v4/anonymous-endpoint,19,4d6b0a93d8b9,0,0
1655925893839,20,/api/v4/anonymous-endpoint,200,,Anonymous Thread Group 1-1,text,true,,1413,370,2,2,http://192.168.50.10:8008/api/v4/anonymous-endpoint,19,4d6b0a93d8b9,0,0
1655925893843,19,/api/v4/anonymous-endpoint,200,,Anonymous Thread Group 1-2,text,true,,1413,370,2,2,http://192.168.50.10:8008/api/v4/anonymous-endpoint,19,4d6b0a93d8b9,0,0
1655925893860,17,/api/v4/anonymous-endpoint,200,,Anonymous Thread Group 1-1,text,true,,1413,370,2,2,http://192.168.50.10:8008/api/v4/anonymous-endpoint,17,4d6b0a93d8b9,0,0
1655925893863,21,/api/v4/anonymous-endpoint,200,,Anonymous Thread Group 1-2,text,true,,1413,370,1,1,http://192.168.50.10:8008/api/v4/anonymous-endpoint,20,4d6b0a93d8b9,0,0
```

```
version: '2.1'

services:
  fe:
    image: novyl/jtl-reporter-fe:latest
    ports:
      - "2020:80"
    depends_on:
      - db
      - be

  db:
    container_name: jtl-reporter-db
    build:
      context: ./db/
      dockerfile: Dockerfile
    volumes:
      - ./data/jtl_reporter_v4:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  be:
    image: novyl/jtl-reporter-be:latest
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - JWT_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhNTAxMjdjMy00ZGYxLTQzMTAtODhhYy0wNWM5OTZhMTFjNjQiLCJpYXQiOjE2NTU4OTk5NTQsImV4cCI6MTY1NjUwNDc1NH0.WIPs6-Cz7e5wtOg9Snr8binliddJbVtUjkVfNH8vvMs # please change this token
      - JWT_TOKEN_LOGIN=token  # please change this token, the same must be used for listener service

  migration:
    image: novyl/jtl-reporter-be:latest
    environment:
      - DATABASE_URL=postgres://postgres@db/jtl_report
    command: npm run migrate up
    depends_on:
      db:
        condition: service_healthy

  listener:
    image: novyl/jtl-reporter-listener-service:latest
    ports:
      - "6000:6000"
    environment:
      - DB_HOST=db
      - JWT_TOKEN=token # paste the same token as in be service - JWT_TOKEN_LOGIN

  scheduler:
    image: novyl/jtl-reporter-scheduler:v0.0.2
    environment:
      - DB_HOST=db
```
