### ISSUE TITLE
Build scheduler container locally

### ISSUE THREAD

**Issue by csvtuda** [ludeknovy/jtl-reporter#161]
Hi,

I'm currently trying to build the JTL reporter locally without depending on the images in Docker Hub. So far I've managed to get everything to work nicely except for the scheduler, because I don't know which Dockerfile the scheduler in Docker Hub was built from.

My `docker-compose-local.yml` currently looks like this (tokens will obviously be changed when everything works):
```yaml
version: '2.1'

services:
  fe:
    container_name: jtl-fe-1
    build:
      context: ./jtl-fe/
      dockerfile: Dockerfile
    ports:
     - "2020:80"
    depends_on:
      - db
      - be

  db:
    container_name: jtl-reporter-db
    build:
      context: ./jtl/db/
      dockerfile: Dockerfile
    volumes:
      - ./jtl/data/jtl_reporter_v4:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  be:
    container_name: jtl-be-1
    build:
      context: ./jtl-be/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - JWT_TOKEN=27JU4qy73hchTMLoH8w9m # please change this token
      - JWT_TOKEN_LOGIN=GdK6TrCvX7rJRZJVg4ijt  # please change this token, the same must be used for listener service

  migration:
    container_name: jtl-migration-1
    build:
      context: ./jtl-be/
      dockerfile: Dockerfile
    environment:
        - WAIT_HOSTS=db:5432 # taken from jtl-be/docker-compose.testing.yaml
        - DATABASE_URL=postgres://postgres@db/jtl_report
    command: sh -c "/wait && npm run migrate up" # taken from jtl-be/docker-compose.testing.yaml
    depends_on:
      db:
        condition: service_healthy

  listener:
    container_name: jtl-listener-1
    build:
      context: ./jtl-listener/
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
    environment:
      - DB_HOST=db
      - JWT_TOKEN=GdK6TrCvX7rJRZJVg4ijt # paste the same token as in be service - JWT_TOKEN_LOGIN
  
  scheduler:
    container_name: jtl-scheduler-1
    build:
      context: ./jtl-be/
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db

```

My folder structure simply looks like this:
```
jtl-reporter/
├─ jtl/
├─ jtl-be/
├─ jtl-fe/
├─ jtl-listener/
├─ docker-compose-local.yml
```

I tried setting the scheduler's context to `jtl-be`, `jtl-fe`, `jtl` and even `jtl-listener`, but it never worked.
I also tried checking the `docker logs` to see if anything is still missing, but I never got them to show this line that the one from Docker Hub contains:
```
> jtl-reporter-scheduler@1.0.0 start
> node dist/index.js
```

Feel free to let me know if you've got an idea of what I'm doing wrong.
