### ISSUE TITLE
Request Statistics Heading Alignment Issue

### ISSUE THREAD

**Issue by kierangirvan** [ludeknovy/jtl-reporter#244]
**Describe the bug**
Whilst viewing a given test run in jtlreporter, specifically under the "Request Statistics", it seems the headings are mis-aligned with the actual values below.

![image](https://github.com/ludeknovy/jtl-reporter/assets/1891193/c0f5353b-f9c3-4291-8865-c85297b935bf)

Notice how there is a random '0' at the end of this example test run, which should be beneath error rate.

Here is the output of the bzt taurus command correctly showing the percentiles:

```
+---------------+---------------+
| Percentile, % | Resp. Time, s |
+---------------+---------------+
|           0.0 |         0.159 |
|          50.0 |         0.209 |
|          90.0 |         0.239 |
|          95.0 |         0.256 |
|          99.0 |         0.301 |
|          99.9 |         0.496 |
|         100.0 |         0.496 |
+---------------+---------------+
15:11:55 INFO: Request label stats:
+---------+--------+---------+--------+-------+
| label   | status |    succ | avg_rt | error |
+---------+--------+---------+--------+-------+
| example |   OK   | 100.00% |  0.213 |       |
+---------+--------+---------+--------+-------+
```

It seems we're missing a median value, as the 50th percentile of 209ms, is now reported under the 90th percentile, and so on hence the misalignment of fields.  This maybe because we include a few additional fields in our jtl csv output:

```
    csv-jtl-flags:
      bytes: true
      sentBytes: true
```

**To Reproduce**

Use the following example bzt file to generate a kpi.jtl and then upload to local install of jtlreporter (we're running 4.8.9):

```
execution:
- hold-for: 120s
  scenario: simple

modules:
  console:
    disable: true
  jmeter:
    gui: false
    properties:
      server.rmi.ssl.disable: true
      log_level: ERROR
    path: ~/.bzt/jmeter-taurus/current/bin/jmeter
    download-link: https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-{version}.zip
    version: 5.5  # minimal supported version of JMeter is 2.9
    force-ctg: true   # true by default
    detect-plugins: true
    csv-jtl-flags:
      bytes: true
      sentBytes: true

settings:
  check-updates: false

scenarios:
  simple:
    requests:
     - label: "example"
       url: https://www.google.com/
```

**Expected behavior**
Statistics to appear under correct headings.
