### ISSUE TITLE
Cannot login as admin

### ISSUE THREAD

**Issue by kamal2222ahmed** [ludeknovy/jtl-reporter#46]
**Describe the bug**
tried to login using 
Default credentials
username: admin
password: 2Txnf5prDknTFYTVEXjj

**To Reproduce**
The only change is in the docker-compose.yml file:
```
version: '2.1'

services:
  fe:
    image: novyl/jtl-reporter-fe:v3.3.5
    ports:
     - "2020:80"
    depends_on:
      - db
      - be
      - mongodb
    networks:
      - mynw

  db:
    image: novyl/jtl-reporter-db
    build:
      context: ./db/
      dockerfile: Dockerfile
    volumes:
      - ./data/jtl_report:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      - DB_HOST=host.docker.localhost
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - mynw

  mongodb:
    image: mongo:4.2.5-bionic
    container_name: jtl-reporter-mongodb
    environment:
      - MONGO_INITDB_DATABASE=jtl-data
    volumes:
      - ./data/jtl_report_mongo:/data/db
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27020:27017"
    networks:
      - mynw
  be:
    image: novyl/jtl-reporter-be:v3.4.0
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=host.docker.internal
      - MONGO_CONNECTION_STRING=mongodb://mongodb:27017
      - JWT_TOKEN=27JU4qy73hchTMLoH8w9m # please change this token
      - JWT_TOKEN_LOGIN=GdK6TrCvX7rJRZJVg4ijt  # please change this token, the same must be used for listener service
    networks:
      - mynw

  migration:
    image: novyl/jtl-reporter-be:v3.4.0
    environment:
        - DB_HOST=host.docker.internal
        - DATABASE_URL=postgres://postgres@db/jtl_report
    command: npm run migrate up
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynw

  listener:
    image: novyl/jtl-reporter-listener-service:v1.0.1
    ports:
      - "6000:6000"
    environment:
      - MONGO_CONNECTION_STRING=mongodb://mongodb:27017
      - JWT_TOKEN=GdK6TrCvX7rJRZJVg4ijt # paste the same token as in be service - JWT_TOKEN_LOGIN
    networks:
      - mynw

networks:
  mynw:
    driver: bridge
```

**Expected behavior**
Be able to login with the credentials provided

**Screenshots**
![image](https://user-images.githubusercontent.com/426822/113564966-3a636880-95d8-11eb-8833-d60cce2d6f23.png)

**Additional context**
docker logs -f 6da9290b6e29
```
{"message":"Unexpected error: Error: connect ECONNREFUSED 192.168.1.2:5432","level":"error"}
{"level":"info","message":"POST /api/auth/login 500 5ms","meta":{}}
{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"192.168.1.2","port":5432,"level":"error"}
{"message":"Unexpected error: Error: connect ECONNREFUSED 192.168.1.2:5432","level":"error"}
{"level":"info","message":"POST /api/auth/login 500 4ms","meta":{}}
{"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"192.168.1.2","port":5432,"level":"error"}
{"message":"Unexpected error: Error: connect ECONNREFUSED 192.168.1.2:5432","level":"error"}
{"level":"info","message":"POST /api/auth/login 500 5ms","meta":{}}
```
This log is from jtl-reporter_be_1
