### ISSUE TITLE
Test results not visible after upload

### ISSUE THREAD

**Issue by kierangirvan** [ludeknovy/jtl-reporter#63]
**Describe the bug**
Having recently upgraded to the latest jtlreporter when I upload my test results via the UI, I am not seeing any results visible in the UI.  I have setup a project, scenario have an api token and upon adding a new test item, I can see the yellow (in progress) count increase to 1, and once finished the green (complete) count still shows 0, and no test results visible.

**To Reproduce**
Launch jtl reporter
Navigate to project > scenario
Click 'Add Test Item'
Choose kpi.jtl (I've attached mine for reference)
Enter an environment i.e. STG
Select Submit

**Expected behavior**
Having clicked Submit - I'd expect to see my test results as per the previous version of jtlreporter.

**Screenshots**
After clicking submit
![Screen Shot 2021-04-28 at 11 59 00 AM](https://user-images.githubusercontent.com/1891193/116393286-5a71fa80-a819-11eb-8a70-e792a787cd86.png)
Once completed
![Screen Shot 2021-04-28 at 11 58 44 AM](https://user-images.githubusercontent.com/1891193/116393259-534aec80-a819-11eb-9a17-238f26524032.png)

**Additional context**
kpi.jtl file for reference (needs to be uncompressed)
[kpi.zip](https://github.com/ludeknovy/jtl-reporter/files/6391305/kpi.zip)

**Comment by kierangirvan** [comment]
I've just checked the logs of the jtl-reporter be and its throwing thousands of theses:
`{"message":"Error while parsing data: not a number","level":"error"}`

**Comment by ludeknovy** [comment]
Hi @kierangirvan Thanks for the detailed report. Will look at it.

**Comment by kierangirvan** [comment]
Thanks @ludeknovy - this is continually happening, and we're currently unable to parse any test results, we've tried a number of different test runs but all are failing with the same reason.  Please let me know if you need anything else to help investigate further.

**Comment by ludeknovy** [comment]
@kierangirvan I think I found the issue - you dont provide "sentBytes" data and the for this reason you get the `Error while parsing data: not a number` and as a result no data gets saved. Check the docs here: https://jtlreporter.site/docs/integrations/introduction

**Comment by kierangirvan** [comment]
Fantastic thanks @ludeknovy - I assume this is a new requirement in the latest jtlreporter?

So is there any guidance on how to add the missing fields to the kpi.jtl, I can see from the link above that it now expects a list of fields which are all not currently being output by default by Taurus (bzt command).  And guidance would be hugely appreciated.

**Comment by ludeknovy** [comment]
You need to set it via Jmeter properties, its mentioned in the docs: https://jtlreporter.site/docs/integrations/introduction ;)

For Taurus check this page: https://gettaurus.org/docs/JMeter/#JMeter-Properties-and-Variables
Let me know whether it worked for you @kierangirvan.

I apologize for adding this breaking change without any notice.

**Comment by kierangirvan** [comment]
Thanks @ludeknovy, I've added the following to my Taurus configuration:
```
modules:
  jmeter:
    properties:
      jmeter.save.saveservice.bytes: true
      jmeter.save.saveservice.elapsed: true
      jmeter.save.saveservice.label: true
      jmeter.save.saveservice.responseCode: true
      jmeter.save.saveservice.responseMessage: true
      jmeter.save.saveservice.threadName: true
      jmeter.save.saveservice.dataType: true
      jmeter.save.saveservice.success: true
      jmeter.save.saveservice.failureMessage: true
      jmeter.save.saveservice.bytes: true
      jmeter.save.saveservice.sentBytes: true
      jmeter.save.saveservice.grpThreads: true
      jmeter.save.saveservice.allThreads: true
      jmeter.save.saveservice.URL: true
      jmeter.save.saveservice.Latency: true
      jmeter.save.saveservice.IdleTime: true
      jmeter.save.saveservice.Connect: true
      jmeter.save.saveservice.Hostname: true
```

And can now see bytes in the kpi.jtl:
```
timeStamp,elapsed,label,responseCode,responseMessage,threadName,success,bytes,grpThreads,allThreads,Latency,Hostname,Connect
1619619723088,4708,SS001 login,200,OK,TwoCheckout-ThreadStarter 1-1,true,2804799,1,1,1094,localhost,1069
1619619728689,1875,SS001 login,200,OK,TwoCheckout-ThreadStarter 1-1,true,2804655,1,1,75,localhost,55
1619619730583,2526,SS001 login,200,OK,TwoCheckout-ThreadStarter 1-1,true,2803707,1,1,78,localhost,51
1619619733115,1855,SS001 login,200,OK,TwoCheckout-ThreadStarter 1-1,true,2803736,1,1,47,localhost,38
1619619734978,1884,SS001 login,200,OK,TwoCheckout-ThreadStarter 1-1,true,2803724,1,1,49,localhost,38
1619619736866,2361,SS001 login,200,OK,TwoCheckout-ThreadStarter 1-1,true,2804743,1,1,58,localhost,40
1619619739234,1997,SS001 login,200,OK,TwoCheckout-ThreadStarter 1-1,true,2803684,1,1,118,localhost,87
1619619741236,1924,SS001 login,200,OK,TwoCheckout-ThreadStarter 1-1,true,2803700,1,1,49,localhost,38
1619619743165,1697,SS001 login,200,OK,TwoCheckout-ThreadStarter 1-1,true,2803722,1,1,49,localhost,36
1619619744866,2179,SS001 login,200,OK,TwoCheckout-ThreadStarter 1-1,true,2804202,1,1,52,localhost,37
1619619747048,1847,SS001 login,200,OK,TwoCheckout-ThreadStarter 1-1,true,2804076,1,1,47,localhost,38
1619619748898,1911,SS001 login,200,OK,TwoCheckout-ThreadStarter 1-1,true,2803714,1,1,48,localhost,38
1619619750813,1982,SS001 login,200,OK,TwoCheckout-ThreadStarter 1-1,true,2803700,1,1,52,localhost,40
1619619752800,2680,SS001 login,200,OK,TwoCheckout-ThreadStarter 1-1,true,2804235,1,1,50,localhost,37
1619619755483,1861,SS001 login,200,OK,TwoCheckout-ThreadStarter 1-1,true,2803708,1,1,63,localhost,52
1619619757347,2174,SS001 login,200,OK,TwoCheckout-ThreadStarter 1-1,true,2804677,1,1,53,localhost,41
```

However, it is still failing to import into the jtlreporter, I must be missing something else.  The exception appears to be the same in the back end container:

```
{"message":"Starting new item processing for scenario: all_shopping","level":"info"}
{"level":"info","message":"POST /api/projects/Example/scenarios/all_shopping/items 200 20ms","meta":{}}
{"message":"Starting KPI file streaming and saving to Mongo with dataId: cf98c32a-ba2b-4244-a71f-7e8add7b3cb8","level":"info"}
{"message":"Error while parsing data: not a number","level":"error"}
{"message":"Error while parsing data: not a number","level":"error"}
{"message":"Error while parsing data: not a number","level":"error"}
{"message":"Error while parsing data: not a number","level":"error"}
{"message":"Error while parsing data: not a number","level":"error"}
{"message":"Error while parsing data: not a number","level":"error"}
{"message":"Error while parsing data: not a number","level":"error"}
{"message":"Error while parsing data: not a number","level":"error"}
{"message":"Error while parsing data: not a number","level":"error"}
{"message":"Error while parsing data: not a number","level":"error"}
{"message":"Error while parsing data: not a number","level":"error"}
{"message":"Error while parsing data: not a number","level":"error"}
{"message":"Error while parsing data: not a number","level":"error"}
{"message":"Parsed 13 records in 0.018 seconds","level":"info"}
{"message":"Error while processing item: 1b1804b8-297d-4f45-9e35-f2a0201df5a6: Error: Error while processing dataId: cf98c32a-ba2b-4244-a71f-7e8add7b3cb8 for item: 1b1804b8-297d-4f45-9e35-f2a0201df5a6, error: Error: Error while processing aggregation pipeline results TypeError: Cannot read property 'start' of undefined","level":"error"}
```

Any help would be greatly appreciated.

**Comment by ludeknovy** [comment]
The "sentBytes" is still not in the sample you provided.

Try this instead: https://gettaurus.org/docs/JMeter/#CSV-file-content-configuration

**Comment by kierangirvan** [comment]
That did the trick thank @ludeknovy - I included the following which ensured the sentBytes was visible in the kpi.jtl and now successfully imported into the jtlreporter.  Thank you so much for your assistance today.

```
modules:
  jmeter:
    csv-jtl-flags:
      xml: false
      fieldNames: true
      time: true
      timestamp: true
      latency: true
      connectTime: true
      success: true
      label: true
      code: true
      message: true
      threadName: true
      dataType: false
      encoding: false
      assertions: false
      subresults: false
      responseData: false
      samplerData: false
      responseHeaders: false
      requestHeaders: false
      responseDataOnError: false
      saveAssertionResultsFailureMessage: false
      bytes: true
      hostname: true
      threadCounts: true
      url: false
      sentBytes: true
```
